name: Fabio Maffioletti
markdown: redcarpet
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
pages_list:
    About: '/'
    Curriculum: '/curriculum'
    Blog: '/blog'
gems:
  - jekyll-sitemap